### ISSUE TITLE
TreasureESP Crash

### ISSUE THREAD

**Issue by parknich** [0xTas/stardust#3] opened 2024-03-30 02:34 UTC
Upon connecting to the queue with TreasureESP enabled, i get the following crash:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-03-29 22:32:44
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_2818 meteordevelopment.meteorclient.events.world.ChunkDataEvent.chunk()'
	at dev.stardust.modules.TreasureESP.onChunkData(TreasureESP.java:151)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_634.handler$ckl000$meteor-client$onChunkData(class_634.java:8526)
	at net.minecraft.class_634.method_11128(class_634.java:740)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	at net.minecraft.class_2600.md578840$f$c$0(class_2600.java:613)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1283)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.stardust.modules.TreasureESP.onChunkData(TreasureESP.java:151)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_634.handler$ckl000$meteor-client$onChunkData(class_634.java:8526)
	at net.minecraft.class_634.method_11128(class_634.java:740)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	at net.minecraft.class_2600.md578840$f$c$0(class_2600.java:613)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
Mixins in Stacktrace:
	net.minecraft.class_634:
		fi.dy.masa.minihud.mixin.MixinClientPlayNetworkHandler (mixins.minihud.json)
		baritone.launch.mixins.MixinClientPlayNetHandler (mixins.baritone.json)
		fi.dy.masa.malilib.mixin.MixinClientPlayNetworkHandler (mixins.malilib.json)
		dev.architectury.mixin.fabric.client.MixinClientPacketListener (architectury.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.world.map.ClientPlayNetworkHandlerMixin (sodium.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.ClientPlayNetworkHandlerMixin (fabric-lifecycle-events-v1.client.mixins.json)
		meteordevelopment.meteorclient.mixin.ClientPlayNetworkHandlerMixin (meteor-client.mixins.json)
		net.futureclient.loader.mixin.common.network.MixinNetHandlerPlayClient (mixins.future.common.json)
		xaero.map.mixin.MixinClientPlayNetworkHandler (xaeroworldmap.mixins.json)
		fi.dy.masa.litematica.mixin.MixinClientPlayNetworkHandler (mixins.litematica.json)
		org.waste.of.time.mixin.ClientPlayNetworkHandlerMixin (worldtools.mixins.common.json)
		net.fabricmc.fabric.mixin.command.client.ClientPlayNetworkHandlerMixin (fabric-command-api-v2.client.mixins.json)
		fi.dy.masa.tweakeroo.mixin.MixinClientPlayNetworkHandler (mixins.tweakeroo.json)
		net.coderbot.iris.mixin.MixinClientPacketListener (mixins.iris.json)
		org.rusherhack.mixin.mixins.common.network.MixinClientPacketListener (mixins.rusherhack.json)
		meteordevelopment.meteorclient.mixin.ClientPlayNetworkHandlerAccessor (meteor-client.mixins.json)
		net.fabricmc.fabric.mixin.attachment.client.ClientPlayNetworkHandlerMixin (fabric-data-attachment-api-v1.client.mixins.json)
		org.rusherhack.client.api.accessors.packet.IMixinClientPacketListener (mixins.rusherhack-accessors.json)
		net.fabricmc.fabric.mixin.networking.client.ClientPlayNetworkHandlerMixin (fabric-networking-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.client.message.ClientPlayNetworkHandlerMixin (fabric-message-api-v1.client.mixins.json)
		xaero.common.mixin.MixinClientPlayNetworkHandler (xaerominimap.mixins.json)
		xaeroplus.mixin.client.mc.MixinClientPlayNetworkHandler (xaeroplus.mixins.json)
		de.florianmichael.viafabricplus.injection.mixin.fixes.minecraft.network.MixinClientPlayNetworkHandler (viafabricplus.mixins.json)
	net.minecraft.class_2600:
		net.futureclient.loader.mixin.common.network.MixinPacketThreadUtil (mixins.future.common.json)

-- Uptime --
Details:
	JVM uptime: 117.663s
	Wall uptime: 62.805s
	High-res time: 43.423s
	Client ticks: 277 ticks / 13.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.class_310:
		meteordevelopment.meteorclient.mixin.MinecraftClientMixin (meteor-client.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		fi.dy.masa.tweakeroo.mixin.MixinMinecraftClient (mixins.tweakeroo.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientAccessor (languagereload.mixins.json)
		fi.dy.masa.minihud.mixin.MixinMinecraftClient (mixins.minihud.json)
		net.futureclient.loader.mixin.baritone.MixinMinecraft (mixins.future.baritone.json)
		de.florianmichael.viafabricplus.injection.mixin.fixes.minecraft.MixinMinecraftClient (viafabricplus.mixins.json)
		xaero.map.mixin.MixinMinecraftClient (xaeroworldmap.mixins.json)
		org.rusherhack.client.api.accessors.client.IMixinMinecraft (mixins.rusherhack-accessors.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		org.rusherhack.mixin.mixins.fabric.MixinMinecraft (mixins.rusherhack-fabric.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		xaeroplus.mixin.client.mc.MixinMinecraftClient (xaeroplus.mixins.json)
		net.futureclient.loader.mixin.common.MixinMinecraft (mixins.future.common.json)
		opekope2.optigui.mixin.MinecraftClientMixin2 (optigui.mixins.json)
		me.redcarlos.higtools.mixins.WindowTitleMixin (higtools.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		meteordevelopment.meteorclient.mixin.MinecraftClientAccessor (meteor-client.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		traben.entity_model_features.mixin.MixinResourceReload (entity_model_features-common.mixins.json)
		dev.stardust.mixin.MinecraftClientMixin (stardust.mixins.json)
		com.github.dimadencep.mods.rrls.mixins.MinecraftClientMixin (rrls-common.mixins.json)
		me.ramidzkh.fabrishot.mixins.MinecraftClientMixin (mixins.fabrishot.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientAccessor (fastquit.mixins.json)
		traben.entity_model_features.mixin.accessor.MinecraftClientAccessor (entity_model_features-common.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl.mixins.json)
		dev.isxander.zoomify.mixins.hooks.MinecraftClientMixin (zoomify.mixins.json)
		baritone.launch.mixins.MixinMinecraft (mixins.baritone.json)
		com.github.dimadencep.mods.rrls.fabric.mixins.MinecraftClientMixin (rrls.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientMixin (languagereload.mixins.json)
		net.futureclient.loader.mixin.common.MixinMinecraft$LowPriority (mixins.future.common.json)
		ru.vidtu.ias.mixins.MinecraftAccessor (ias.mixins.json)
		fi.dy.masa.litematica.mixin.MixinMinecraftClient (mixins.litematica.json)
		xaero.common.mixin.MixinMinecraftClient (xaerominimap.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (sodium.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientMixin (fastquit.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.core.MixinMinecraftClient (immediatelyfast-common.mixins.json)
		de.florianmichael.viafabricplus.injection.mixin.base.integration.MixinMinecraftClient (viafabricplus.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		kassuk.addon.blackout.mixins.AccessorMinecraftClient (blackout.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin (optigui.mixins.json)
		org.rusherhack.mixin.mixins.common.client.MixinMinecraft (mixins.rusherhack.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
	net.minecraft.client.main.Main:
		org.rusherhack.mixin.mixins.common.client.MixinMain (mixins.rusherhack.json)
		de.florianmichael.viafabricplus.injection.mixin.base.MixinMain (viafabricplus.mixins.json)

-- Affected level --
Details:
	All players: 1 total; [class_746['parknich'/40376, l='ClientLevel', x=0.50, y=64.00, z=0.50]]
	Chunk stats: 1024, 0
	Level dimension: minecraft:the_end
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 18245 day time
	Server brand: 2b2t (Velocity) (ZenithProxy)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 1

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, programmer_art, fabric, advanced-xray-fabric, blackout, caffeineconfig, capes, cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, continuity, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabrishot, fastquit, higtools, ias, immediatelyfast, indium, iris, languagereload, litematica, lithium, malilib, meteor-client, minihud, mixintrace, moddetectionpreventer, modmenu, modmenu_programmer_art, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, optigui, reeses-sodium-options, rrls, serverseeker, shulkerboxtooltip, skinlayers3d, sodium, sodium-extra, sodium_programmer_art, stardust, tweakeroo, viafabricplus, worldedit, worldtools, xaerominimap, xaeroplus, xaeroworldmap, yet_another_config_lib_v3, yosbr, zoomify, file/SodiumTranslations.zip, file/Mod Menu Helper.zip, file/Chat Reporting Helper.zip, file/VanillaTweaks_r853353, file/Programmer Art Ultimate 1.20, file/FreshAnimations_v1.8.1.zip

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.7, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1365379952 bytes (1302 MiB) / 3221225472 bytes (3072 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12600K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: Parsec Virtual Display Adapter
	Graphics card #0 vendor: Parsec Cloud, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=0.41.0.0
	Graphics card #1 name: Virtual Desktop Monitor
	Graphics card #1 vendor: Virtual Desktop, Inc.
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=15.39.56.845
	Graphics card #2 name: NVIDIA GeForce GTX 1070
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 4095.00
	Graphics card #2 deviceId: 0x1b81
	Graphics card #2 versionInfo: DriverVersion=31.0.15.4633
	Graphics card #3 name: Intel(R) UHD Graphics 770
	Graphics card #3 vendor: Intel Corporation (0x8086)
	Graphics card #3 VRAM (MB): 128.00
	Graphics card #3 deviceId: 0x4680
	Graphics card #3 versionInfo: DriverVersion=31.0.101.5186
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 61170.97
	Virtual memory used (MB): 46481.58
	Swap memory total (MB): 28615.10
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx6144m
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 84.0.0
		architectury: Architectury 11.0.12
		baritone: Baritone 1.10.2
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.4.1
		blackout: Blackout 1.0.2
		capes: Capes 1.5.3+1.20.2
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.4+1.20.2
		entity_model_features: Entity Model Features 1.2.3
		entity_texture_features: Entity Texture Features 5.2.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.96.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.13+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.0+32782cfd4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.1+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.23+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.63+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.11+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.0+d74054c14f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.10+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fabrishot: Fabrishot 1.12.1
		fastquit: FastQuit 3.0.0+1.20.4
		ferritecore: FerriteCore 6.0.3
		higtools: HIGTools 2.7.1
		ias: In-Game Account Switcher 8.0.2
		immediatelyfast: ImmediatelyFast 1.2.10+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		indium: Indium 1.0.30+mc1.20.4
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		languagereload: Language Reload 1.5.10+1.20.3
		litematica: Litematica 0.17.0
		lithium: Lithium 0.12.1
		malilib: MaLiLib 0.18.0
		meteor-client: Meteor Client 0.5.6-2024
		minecraft: Minecraft 1.20.4
		minihud: MiniHUD 0.30.0
		mixintrace: MixinTrace 1.1.1+1.17
		moddetectionpreventer: ModDetectionPreventer 1.1.0
		modelfix: Model Gap Fix 1.14
		modmenu: Mod Menu 9.0.0
		optigui: OptiGUI 2.1.7
			optiglue: OptiGlue 2.1.7-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.4-build.102
		rrls: Remove Reloading Screen 3.3.0+mc1.20.4-fabric
		rusherhack: RusherHack Fabric Loader 1.0
		serverseeker: ServerSeeker 4.3.0
		shulkerboxtooltip: Shulker Box Tooltip 4.0.8+1.20.4
		skinlayers3d: 3d-Skin-Layers 1.6.2
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		stardust: Stardust 1.5.0
		tweakeroo: Tweakeroo 0.19.1
		viafabricplus: ViaFabricPlus 3.0.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 4.10.0-23w51b-SNAPSHOT
			com_viaversion_viaversion-common: viaversion-common 4.10.0-23w51b-SNAPSHOT
			de_florianmichael_classic4j: Classic4J 2.0.1
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.3
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.3
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.3
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_raphimc_minecraftauth: MinecraftAuth 3.1.0
			net_raphimc_viaaprilfools: ViaAprilFools 2.0.11-SNAPSHOT
			net_raphimc_viabedrock: ViaBedrock 0.0.4-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 2.2.22-SNAPSHOT
			net_raphimc_vialoader: ViaLoader 2.2.13-SNAPSHOT
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR1-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
		whoami: Who am I? 1.0
		worldedit: WorldEdit 7.3.0+6678-55745ad
		worldtools: WorldTools 1.2.4
		xaerominimap: Xaero's Minimap 23.9.7
		xaeroplus: XaeroPlus 1.20.4
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			net_lenni0451_lambdaevents: LambdaEvents 2.4.1
		xaeroworldmap: Xaero's World Map 1.37.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.13.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: (off)
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.33, NVIDIA Corporation
	Window size: 1920x1200
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 6/6 chunks
	Resource Packs: vanilla, programmer_art, fabric, file/SodiumTranslations.zip, file/Mod Menu Helper.zip, file/Chat Reporting Helper.zip, file/VanillaTweaks_r853353, file/Programmer Art Ultimate 1.20 (incompatible), file/FreshAnimations_v1.8.1.zip (incompatible)
	Current Language: en_us
	Locale: en_US
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-12600K

-- Meteor Client --

Version: 0.5.6
Dev Build: 2024

[[ Active Modules ]]

[Player]:
auto-gap

[Render]:
no-render
pop-chams
trajectories

[World]:
build-height
enderman-look
no-ghost-blocks

[BlackOut]:
Mine ESP,

[Settings]:
Facing
Range

[HIG Tools]:
HIG-prefix

[Stardust]:
BannerData
Honker
SignatureSign
TreasureESP

[[ Active Hud Elements ]]
Text
{{meteor.name} #1{meteor.version}}
active-modules
Text
{{player.opposite_dimension != "End" ? player.opposite_dimension + ":" : ""} #1{player.opposite_dimension != "End" ? "" + floor(camera.opposite_dim_pos.x) + ", " + floor(camera.opposite_dim_pos.y) + ", " + floor(camera.opposite_dim_pos.z) : ""}}

**Comment by 0xTas** [comment] 2024-03-30 03:27
What versions of meteor, stardust, and minecraft are you using? I cannot reproduce your issue.

**Comment by 0xTas** [comment] 2024-03-30 03:36
Oh I see the meteor version there. Try a newer dev build of meteor and let me know if it still happens.

**Comment by 0xTas** [comment] 2024-03-30 03:42
The issue you're likely experiencing was fixed in https://github.com/MeteorDevelopment/meteor-client/commit/484b2cf4eec460fd13d1eaee8555f24a05002bdc

**Comment by 0xTas** [comment] 2024-04-01 00:34
Gonna assume this is resolved.

**Closed by 0xTas** 2024-04-01 00:34 UTC
